//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railwaytrackingandtimings
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RailwaytrackingEntitieslatest : DbContext
    {
        public RailwaytrackingEntitieslatest()
            : base("name=RailwaytrackingEntitieslatest")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblStationDetail> tblStationDetails { get; set; }
        public virtual DbSet<tblTrainDetail> tblTrainDetails { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserStation> tblUserStations { get; set; }
        public virtual DbSet<StationTrainDetail> StationTrainDetails { get; set; }
        public virtual DbSet<TemptblStationTrainDetail> TemptblStationTrainDetails { get; set; }
        public virtual DbSet<TblRating> TblRatings { get; set; }
        public virtual DbSet<tblNotification> tblNotifications { get; set; }
        public virtual DbSet<tblEmailNotification> tblEmailNotifications { get; set; }
    
        public virtual ObjectResult<Usp_rating_Result> Usp_rating(string stationCode)
        {
            var stationCodeParameter = stationCode != null ?
                new ObjectParameter("StationCode", stationCode) :
                new ObjectParameter("StationCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_rating_Result>("Usp_rating", stationCodeParameter);
        }
    
        public virtual ObjectResult<usp_Notifications_Result> usp_Notifications()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Notifications_Result>("usp_Notifications");
        }
    
        public virtual ObjectResult<usp_NotificationsUpdate_Result> usp_NotificationsUpdate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_NotificationsUpdate_Result>("usp_NotificationsUpdate");
        }
    }
}
