//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railwaytrackingandtimings
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RailwaytrackingEntitieslatest : DbContext
    {
        public RailwaytrackingEntitieslatest()
            : base("name=RailwaytrackingEntitieslatest")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblStationDetail> tblStationDetails { get; set; }
        public virtual DbSet<tblTrainDetail> tblTrainDetails { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserStation> tblUserStations { get; set; }
        public virtual DbSet<StationTrainDetail> StationTrainDetails { get; set; }
        public virtual DbSet<TemptblStationTrainDetail> TemptblStationTrainDetails { get; set; }
        public virtual DbSet<TblRating> TblRatings { get; set; }
        public virtual DbSet<tblNotification> tblNotifications { get; set; }
        public virtual DbSet<tblEmailNotification> tblEmailNotifications { get; set; }
    }
}
