//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railwaytrackingandtimings
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRating
    {
        public int Id { get; set; }
        public string StationCode { get; set; }
        public int Maintance { get; set; }
        public int Security { get; set; }
        public int Food { get; set; }
        public string Staff { get; set; }
    }
}
