//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railwaytrackingandtimings
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainDetail
    {
        public int TrainId { get; set; }
        public string TrainName { get; set; }
        public string TrainType { get; set; }
        public string FromStationcode { get; set; }
        public string ToStationCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string Status { get; set; }
    
        public virtual tblStationDetail tblStationDetail { get; set; }
        public virtual tblStationDetail tblStationDetail1 { get; set; }
    }
}
