//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railwaytrackingandtimings
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tblUser
    {

        [Display(Name = "User Id")]
        [Required(ErrorMessage = "Enter UserId")]
        public string UserId { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Enter Password")]
        public string Password { get; set; }
        [NotMapped] // Does not effect with your database
        [Compare("Password")]
        [Required(ErrorMessage = "Enter Confirm Password")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Enter First Name")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Enter Last Name")]
        public string LastName { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public int Role { get; set; }
    
        public virtual tblRole tblRole { get; set; }
    }
}
