//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railwaytrackingandtimings
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TemptblStationTrainDetail
    {
        [Display(Name="Train No")]
        public int TrainId { get; set; }
        [Display(Name = "Station Code")]
        public string StationCode { get; set; }
        [Display(Name = "Schdule Date")]
        public System.DateTime SchduleDate { get; set; }
        [Display(Name = "Arrival Time")]
        public System.TimeSpan ArrivalTime { get; set; }
        [Display(Name = "Depature Time")]
        public System.TimeSpan DepatureTime { get; set; }
        public string Status { get; set; }
        public string StationName { get; set; }
        public int Id { get; set; }
    }
}
